In [89]:
import cv2

In [90]:
import numpy as np

In [91]:
URL = 'https://nnfs.io/datasets/fashion_mnist_images.zip'
FILE = 'fashion_mnist_images.zip'
FOLDER = 'fashion_mnist_images'

In [92]:
import os
labels = os.listdir(f'{FOLDER}/train')
labels

['.DS_Store', '9', '0', '7', '6', '1', '8', '4', '3', '2', '5']

In [93]:
image_data = cv2.imread(f'{FOLDER}/train/7/0002.png', cv2.IMREAD_UNCHANGED)

In [94]:
image_data.shape

(28, 28)

In [95]:
image_data

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [96]:
def load_data(dataset, path):
    data = os.listdir(f'{path}/{dataset}')
    labels = list(filter(lambda x : x != ".DS_Store", data))
    print(labels)
    X = []
    y = []
    for label in labels:
        for file in os.listdir(f'{path}/{dataset}/{label}'):
            image = cv2.imread(os.path.join(path, dataset, label, file), cv2.IMREAD_UNCHANGED)
            X.append(image)
            y.append(label)
    return np.array(X), np.array(y).astype(int)


In [97]:
def prepare_data(path):
    X,y = load_data('train', path)
    X_test, y_test = load_data('test', path)
    return X,y,X_test, y_test

In [98]:
def pre_processData():
    X,y,X_test,y_test=prepare_data(f'fashion_mnist_images')
    scale = 255/2
    X = (X.astype(dtype=float) - scale) /scale
    X_test = (X_test.astype(dtype=float) - scale)/scale
    return X,y,X_test,y_test

In [99]:
X,y,X_test,y_test = pre_processData()

['9', '0', '7', '6', '1', '8', '4', '3', '2', '5']
['9', '0', '7', '6', '1', '8', '4', '3', '2', '5']


In [100]:
X[0]

array([[-1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.    

In [101]:
X.min(), X.max()

(-1.0, 1.0)

In [102]:
X.shape

(60000, 28, 28)

In [347]:
dummy_images = np.array(
    [
                   [[1,2,3,4,5,6],
                   [6,8,9,10,11,6],
                   [12,13,14,15,16,6],
                   [17,18,19,20,21,6],
                   [22,23,24,25,26,6],
                    [22,23,24,25,26,6]],
        [[1,2,3,4,5,6],
         [6,8,9,10,11,6],
         [12,13,14,15,16,6],
         [17,18,19,20,21,6],
         [22,23,24,25,26,6],
         [22,23,24,25,26,6]]
])
print(dummy_images.shape)

(2, 6, 6)


In [348]:
filters = np.array([[[1,2,1],
                    [3,2,1],
                    [2,1,3]],
                    [[1,1,3],
                     [2,1,3],
                     [1,2,3]]])
filters.shape
dummy_images.shape[0]

2

In [349]:
def im2col_sliding_strided(A, BSZ, stepsize=1):
    # Parameters
    m,n = A.shape
    s0, s1 = A.strides
    nrows = m-BSZ[0]+1
    ncols = n-BSZ[1]+1
    shp = BSZ[0],BSZ[1],nrows,ncols
    strd = s0,s1,s0,s1

    out_view = np.lib.stride_tricks.as_strided(A, shape=shp, strides=strd)
    return out_view.reshape(BSZ[0]*BSZ[1],-1)[:,::stepsize]

In [350]:
for image in range(len(dummy_images)):
    dummy = dummy_images[image]
    result = im2col_sliding_strided(dummy, [3,3])
    print(result.shape)
    print(filters.shape)
    filters2 = filters.reshape(2,-1)
    im_result = np.dot(filters2, result)
    im_result.reshape(2,3,3)
    result

(9, 16)
(2, 3, 3)


ValueError: cannot reshape array of size 32 into shape (2,3,3)

In [351]:
gradient = np.array([
    [
        [4,4,4],
        [5,5,5],
        [6,6,6]
    ],
    [
        [1, 1, 1],
        [9, 9, 9],
        [5, 5, 5]
    ]
])

dl = gradient.reshape(2, -1)
dl_filters = []
for i in range(len(dl)):
    item = dl[i]*result
    item = item.sum(axis=0)
    item =item.reshape(3,3)
    dl_filters.append(item)
dl_filters = np.array(dl_filters)
dl_filters.shape

ValueError: operands could not be broadcast together with shapes (9,) (9,16) 

In [403]:
gradient = np.array([
    [
        [4,4,4,4],
        [5,5,5,4],
        [6,6,6,4],
        [1,1,1,3]
    ],
    [
        [1, 1, 1,1],
        [2, 2, 2,2],
        [3, 3, 3,3],
        [2,2,2,2]
    ],
    [
        [5,5,5,5],
        [5,5,5,4],
        [6,6,6,4],
        [1,1,1,3]
    ],
    [
        [1, 1, 1,1],
        [2, 2, 2,2],
        [3, 3, 3,3],
        [2,2,2,2]
    ],
])
gradient.shape
res = gradient.reshape(2,2,4,4)
res[0].reshape(2,-1)

array([[4, 4, 4, 4, 5, 5, 5, 4, 6, 6, 6, 4, 1, 1, 1, 3],
       [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 2, 2, 2, 2]])

In [404]:
class Conv_Layer:
    def __init__(self, num_filters, filterSize):
        self.num_filters = num_filters
        self.filters = np.random.randn(num_filters, filterSize, filterSize)
       # self.filters[1] = np.zeros(self.filters[1].shape)
        self.filterSize = filterSize
        self.im2cols = []
        self.outputSize = 0
        self.inputChannelLength = 0
    def forward(self, input_channels, spatialSize):
        outputSize = spatialSize - self.filterSize + 1
        self.inputChannelLength = len(input_channels)
        self.outputSize = outputSize
        for image in range(len(input_channels)):
            featureMap = input_channels[image]
            result = im2col_sliding_strided(featureMap, [self.filterSize, self.filterSize])
            self.im2cols.append(result)
        self.im2cols = np.array(self.im2cols)
       # print(self.im2cols.shape)
        conv = np.dot(self.filters.reshape(1,self.num_filters, -1), self.im2cols)
        #print(self.filters.reshape(1,self.num_filters, -1).shape, self.im2cols.shape, conv.shape)
        #print("***** filter shape ****",self.num_filters,len(input_channels), outputSize, outputSize, conv.shape)
        self.output = conv.reshape(self.num_filters*len(input_channels), outputSize, outputSize)
        #print(self.output)
    def backward(self, dlInput):
        dl = dlInput.reshape(self.num_filters,self.inputChannelLength, self.outputSize, self.outputSize)
        print(dl.shape)
        for i in range(len(dl)):
            print(i)
            #compte gradient sequentially
            im2loc = self.im2cols[i]
            print(len(self.im2cols))
            reshapedGradient = dl[i].reshape(len(self.im2cols), -1)
            print(reshapedGradient.shape)
            lastItem = np.array([])
            print("---- reshaped gradient ----")
            print(reshapedGradient)
            for j in range(len(reshapedGradient)):
                item = reshapedGradient[j]*self.im2cols[j]
                item = item.sum(axis=0)
                if len(lastItem) > 1:
                    lastItem = lastItem + item
                else:
                    lastItem = item
            print("---- gradient sum -----")
            print(lastItem)




"""
dl_filters = []
for i in range(len(dl)):
    item = dl[i]*self.im2col
    item = item.sum(axis=0)
    item =item.reshape(3,3)
    dl_filters.append(item)
dl_filters = np.array(dl_filters)
"""



'\ndl_filters = []\nfor i in range(len(dl)):\n    item = dl[i]*self.im2col\n    item = item.sum(axis=0)\n    item =item.reshape(3,3)\n    dl_filters.append(item)\ndl_filters = np.array(dl_filters)\n'

In [405]:
layer1 = Conv_Layer(2, 3)
layer1.forward(dummy_images,6)
layer1.backward(gradient)
print("---------- layer 1 --------")
#print(layer1.output.shape)
layer2 = Conv_Layer(2,3)
layer2.forward(layer1.output,4)
#print("======= layer 2 =======")
#print(layer2.output)



(2, 2, 4, 4)
0
2
(2, 16)
---- reshaped gradient ----
[[4 4 4 4 5 5 5 4 6 6 6 4 1 1 1 3]
 [1 1 1 1 2 2 2 2 3 3 3 3 2 2 2 2]]
---- gradient sum -----
[ 340  390  435  395  812  882  945  666 1458 1539 1620  987  576  603
  630  805]
1
2
(2, 16)
---- reshaped gradient ----
[[5 5 5 5 5 5 5 4 6 6 6 4 1 1 1 3]
 [1 1 1 1 2 2 2 2 3 3 3 3 2 2 2 2]]
---- gradient sum -----
[ 408  468  522  474  812  882  945  666 1458 1539 1620  987  576  603
  630  805]
---------- layer 1 --------


In [370]:
dummy_images.shape

(2, 6, 6)

In [315]:
class Conv_Layer2:
    def __init__(self, num_filters, filterSize):
        self.num_filters = num_filters
        self.filters = np.random.randn(num_filters, filterSize, filterSize)
        self.filterSize = filterSize
        self.im2cols = []
    def forward(self, input_channels, spatialSize):
        outputSize = spatialSize - self.filterSize + 1
        for image in range(len(input_channels)):
            featureMap = input_channels[image]
            result = im2col_sliding_strided(featureMap, [self.filterSize, self.filterSize])
            self.im2cols.append(result)
        self.im2cols = np.array(self.im2cols)
        print(self.im2cols.shape)
        conv = np.dot(self.filters.reshape(1,self.num_filters, -1), self.im2cols)
        print("***** filter shape ****",self.num_filters,len(input_channels), outputSize, outputSize, conv.shape)
        self.output = conv.reshape(self.num_filters*len(input_channels), outputSize, outputSize)
        print(self.output)
    def backward(self, dlInput):
        dl = dlInput.reshape(self.num_filters, -1)
        dl_filters = []
        for i in range(len(dl)):
            item = dl[i]*self.im2col
            item = item.sum(axis=0)
            item =item.reshape(3,3)
            dl_filters.append(item)
        dl_filters = np.array(dl_filters)


In [321]:
dummy_images = np.array(
    [
        [[1,2,3,4,5,6],
         [6,8,9,10,11,6],
         [12,13,14,15,16,6],
         [17,18,19,20,21,6],
         [22,23,24,25,26,6],
         [22,23,24,25,26,6]],
        [[1,2,3,4,5,6],
         [6,8,9,10,11,6],
         [12,13,14,15,16,6],
         [17,18,19,20,21,6],
         [22,23,24,25,26,6],
         [22,23,24,25,26,6]]
    ])
dummy_images.shape

(2, 6, 6)

In [322]:
dummy_images.reshape(1,2,6,6)

array([[[[ 1,  2,  3,  4,  5,  6],
         [ 6,  8,  9, 10, 11,  6],
         [12, 13, 14, 15, 16,  6],
         [17, 18, 19, 20, 21,  6],
         [22, 23, 24, 25, 26,  6],
         [22, 23, 24, 25, 26,  6]],

        [[ 1,  2,  3,  4,  5,  6],
         [ 6,  8,  9, 10, 11,  6],
         [12, 13, 14, 15, 16,  6],
         [17, 18, 19, 20, 21,  6],
         [22, 23, 24, 25, 26,  6],
         [22, 23, 24, 25, 26,  6]]]])

In [343]:
first = np.array([[1,2],
                  [1,1]])
second = np.array([[
    [1,1],
    [1,1]
],
[
  [2,2],
    [2,2]
]])
print(first.shape)
print(second.shape)

(2, 2)
(2, 2, 2)


In [345]:
first = first.reshape(2,1,2)
first

array([[[1, 2]],

       [[1, 1]]])

In [346]:
np.dot(first, second)

array([[[[3, 3],
         [6, 6]]],


       [[[2, 2],
         [4, 4]]]])